// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA510CB5pTKQki4Vsmcr0noDGP7sbW4srw',
    appId: '1:628873519207:web:704274a68673b3872cb4c2',
    messagingSenderId: '628873519207',
    projectId: 'trabajo-final2-d855d',
    authDomain: 'trabajo-final2-d855d.firebaseapp.com',
    storageBucket: 'trabajo-final2-d855d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9zn39u1JP5k3-qwt1qFXveVd9Jr_exPU',
    appId: '1:628873519207:android:f66ccc148b01ff852cb4c2',
    messagingSenderId: '628873519207',
    projectId: 'trabajo-final2-d855d',
    storageBucket: 'trabajo-final2-d855d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Gwq0L04etNfOapNfVydzcUfiWOSFyho',
    appId: '1:628873519207:ios:2532443293e231732cb4c2',
    messagingSenderId: '628873519207',
    projectId: 'trabajo-final2-d855d',
    storageBucket: 'trabajo-final2-d855d.appspot.com',
    iosBundleId: 'com.example.trabajo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Gwq0L04etNfOapNfVydzcUfiWOSFyho',
    appId: '1:628873519207:ios:2532443293e231732cb4c2',
    messagingSenderId: '628873519207',
    projectId: 'trabajo-final2-d855d',
    storageBucket: 'trabajo-final2-d855d.appspot.com',
    iosBundleId: 'com.example.trabajo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA510CB5pTKQki4Vsmcr0noDGP7sbW4srw',
    appId: '1:628873519207:web:07785ee3068db84b2cb4c2',
    messagingSenderId: '628873519207',
    projectId: 'trabajo-final2-d855d',
    authDomain: 'trabajo-final2-d855d.firebaseapp.com',
    storageBucket: 'trabajo-final2-d855d.appspot.com',
  );

}